language: cpp
dist: trusty
sudo: required
compiler: gcc

env:
  global:
   - secure: "A/AEz62FUk3Hh+5t3ekl3vZqjiNS9ttzBhelc+vLx8/P4PeFXXJcNmaIHhfkzf17aUPI0Hfb7Dui9YPLVGS9CwjY9m9jGY6MStXSIHQP2eT1TfazSCUckDstcWJ37hvgKqay9ZoqwzFryXKRNe/X4nOl4GzMBRRWLOxctf/MEqhIq1cw7ZAXzLGpvQMroc2JYM1Kz0n/6nR5v+4WCTEdq/lML0J7dXZKQ7RZFT180PoZpqlI4fEzDma9aJIb85NBH7jD8x/YXeTcQ/ZSZSJ5rOAobRgHuLLxFODryNK7zJ/1WVLexqLhiaspximqe/7f9poi9Kxl2tuCV7sIV1Wqjo1qBILMAaoYx2+hMmoKpn1BOdIzLFBJYJUGGJ5egBHJpdlbt0hAP8TmPBQ3lAgJBgdBmwmCI8lCiNEevpMa5Cv4qE+xXgrcccxDu6N3U2SNyO2sZBJlnT1ZsO2B3+ALNYXnfBZUznPnHkfFBSw4nuboVsTnciKEaymWKmiZG9Uvo68FWsb5cCM/xqYb7soRYhb++1JTJj+DEbJm4k1clnGuqpTk7CSy9uPL0LZjJu4aRSsLf5cQ9tvKf1wPsn63lFjUInlAEHqZLwSioHw7X2WwhGcM5hHG6HDX1P/6xdH/Ud5y8zvvXvkRxSotPckzmoWTzt2VavFlNDHa2g9qJHo="

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-6
      - gcc-6
  coverity_scan:
    project:
      name: "poppeman/Pictus"
      description: "Build submitted via Travis CI"
    notification_email: pontus@mardnas.se
    build_command_prepend: "cov-configure --comptype gcc --compiler /usr/bin/g++-6; mkdir coverity; cd coverity; cmake .."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libjpeg-turbo8-dev libpng12-dev zlib1g-dev libtiff5-dev libboost1.55-all-dev libglew-dev libwxgtk3.0-dev libwebp-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
      then
        echo "Don't build on coverty_scan branch.";
        exit 0;
    fi
  - mkdir build
  - cd build
  - cmake .. -DENABLE_CODE_COVERAGE && make -j 4
  - make
  - make test
  - gcov-6 `find . -name *.gcno`
  - codecov

