language: cpp
dist: trusty
sudo: required
compiler: gcc

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libjpeg-turbo8-dev libpng12-dev zlib1g-dev libtiff5-dev libboost1.55-all-dev libglew-dev libwxgtk3.0-dev libwebp-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - mkdir build
  - cd build
  - cmake .. && make
  - ./bin/illaTest ../bin/Test
  - ./bin/orzTest ../bin/Test
  - ./bin/pictusTest ../bin/Test

